In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression as LR # 線形回帰のモデル
%matplotlib inline # notebook上でグラフを表示するおまじない


UsageError: unrecognized arguments: # notebook上でグラフを表示するおまじない


In [2]:
%matplotlib inline

In [3]:
train = pd.read_csv['train.csv']

TypeError: 'function' object is not subscriptable

In [4]:
train = pd.read_csv("train.csv")

In [5]:
train.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

In [6]:
train.describe()

y     soldout        kcal  payday  temperature
count  207.000000  207.000000  166.000000    10.0   207.000000
mean    86.623188    0.449275  404.409639     1.0    19.252174
std     32.882448    0.498626   29.884641     0.0     8.611365
min     29.000000    0.000000  315.000000     1.0     1.200000
25%     57.000000    0.000000  386.000000     1.0    11.550000
50%     78.000000    0.000000  408.500000     1.0    19.800000
75%    113.000000    1.000000  426.000000     1.0    26.100000
max    171.000000    1.000000  462.000000     1.0    34.600000

In [7]:
X_train = train['temperature']
y_train = train['y']
X_test  = test['temperature']

NameError: name 'test' is not defined

In [8]:
test=pd.read_csv("test.csv")

In [9]:
X_test  = test['temperature']

In [10]:
X_train.head()

0    19.8
1    17.0
2    15.5
3    15.2
4    16.1
Name: temperature, dtype: float64

In [11]:
X_train.head()

0    19.8
1    17.0
2    15.5
3    15.2
4    16.1
Name: temperature, dtype: float64

In [12]:
X_train.shape()

TypeError: 'tuple' object is not callable

In [13]:
X_train.shape

(207,)

In [14]:
X_train.head()

0    19.8
1    17.0
2    15.5
3    15.2
4    16.1
Name: temperature, dtype: float64

In [15]:
X_train.values


array([ 19.8,  17. ,  15.5,  15.2,  16.1,  14.6,  17.9,  14.7,  17.7,
        12.1,  13.8,  13.9,  13.5,  13.8,  14.9,   9.1,   7.1,  11. ,
        12.3,  13.9,  11.3,  10.8,   7.8,   6.8,   8.4,  11.5,   8. ,
         7.3,   7.3,   9.8,  10.9,   5.1,   5.8,   2.9,   7. ,   7.8,
         6.5,  10.4,   7.4,   8.5,  10.1,   5.1,  12.6,  10.3,  15.3,
        14.1,  15.9,   3.8,   3. ,   4.2,   5.5,   7.8,   6.3,   6.4,
         1.2,  11.6,   6.8,   7.3,   5.4,   8.5,   6.6,  10.5,  11.5,
         8.5,  17.7,   7.8,   8.3,   6.1,   6.7,   7. ,   7.6,   8.7,
        14.8,  15.2,  11.5,  14. ,  18.9,  12.6,   7.5,  17.4,  18.9,
        18.7,  12.4,  18.5,  17.5,  16.1,  18.2,  14.3,  17.8,  13.8,
        20.1,  19. ,  21.3,  16.5,  16.4,  19.7,  21.5,  20.1,  11.4,
        16.4,  18.8,  19.4,  19.9,  20.8,  22.7,  17.5,  24. ,  23.3,
        18.9,  21. ,  23.4,  22.7,  18.6,  26. ,  19.3,  23.8,  22.8,
        23.9,  17.4,  19. ,  19.8,  23.9,  23.7,  25.7,  26. ,  26.9,
        30.6,  27. ,

In [16]:
X_train=X_train.values.reshape(-1,1)

In [17]:
X_train

array([[ 19.8],
       [ 17. ],
       [ 15.5],
       [ 15.2],
       [ 16.1],
       [ 14.6],
       [ 17.9],
       [ 14.7],
       [ 17.7],
       [ 12.1],
       [ 13.8],
       [ 13.9],
       [ 13.5],
       [ 13.8],
       [ 14.9],
       [  9.1],
       [  7.1],
       [ 11. ],
       [ 12.3],
       [ 13.9],
       [ 11.3],
       [ 10.8],
       [  7.8],
       [  6.8],
       [  8.4],
       [ 11.5],
       [  8. ],
       [  7.3],
       [  7.3],
       [  9.8],
       [ 10.9],
       [  5.1],
       [  5.8],
       [  2.9],
       [  7. ],
       [  7.8],
       [  6.5],
       [ 10.4],
       [  7.4],
       [  8.5],
       [ 10.1],
       [  5.1],
       [ 12.6],
       [ 10.3],
       [ 15.3],
       [ 14.1],
       [ 15.9],
       [  3.8],
       [  3. ],
       [  4.2],
       [  5.5],
       [  7.8],
       [  6.3],
       [  6.4],
       [  1.2],
       [ 11.6],
       [  6.8],
       [  7.3],
       [  5.4],
       [  8.5],
       [  6.6],
       [ 10.5],
       [

In [18]:
X_train.shape

(207, 1)

In [19]:
model=LR()

In [20]:
y_train

0       90
1      101
2      118
3      120
4      130
5      135
6      145
7      140
8      151
9      116
10     151
11     153
12     151
13     171
14     134
15     165
16     155
17     157
18     109
19     111
20     160
21     145
22     145
23     151
24     134
25     122
26     121
27      80
28     131
29     128
      ... 
177     56
178     53
179     56
180     54
181    100
182     55
183     68
184     62
185     56
186     39
187     65
188     68
189     53
190     54
191     43
192     68
193     63
194     54
195     53
196    115
197     56
198     49
199     46
200     45
201     29
202     59
203     50
204     45
205     56
206     40
Name: y, Length: 207, dtype: int64

In [21]:
mode.fit(X_train.y_train)

NameError: name 'mode' is not defined

In [22]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
mode.coef_

NameError: name 'mode' is not defined

In [24]:
model.coef_

array([-2.5023821])

In [25]:
mode.intercept_

NameError: name 'mode' is not defined

In [26]:
model.intercept_

134.79948383749925

In [27]:
model.score

<bound method RegressorMixin.score of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)>

In [28]:
model.score(X_train,y_train)

0.42946028151941368